---

version: '3.2'
services:

  anpr-dashboard:
    container_name: anpr-dashboard
    image: teamdigitale/anpr-dashboard
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
